# Generated by Django 4.2.3 on 2023-07-21 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('noticias', '0001_initial'),
    ]

    operations = [
      ##  migrations.AddField(
      ##      model_name='noticia',
      ##      name='creador',
      ##      field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarios'),
      ##  ),
    ]
