# Generated by Django 4.2.3 on 2023-07-27 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_creador'),
    ]

    operations = [
        ##migrations.RemoveField(
        ##    model_name='noticia',
        ##    name='creador',
        ##),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(default='Sin categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticias.categoria', verbose_name='Categoria'),
        ),
    ]
