# Generated by Django 4.2.3 on 2023-07-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_remove_noticia_creador_noticia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='noticias/noticia-default.png', upload_to='noticias'),
        ),
    ]
