# Generated by Django 4.2.3 on 2023-07-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_remove_noticia_creador_alter_noticia_categoria'),
        ('noticias', '0004_alter_noticia_imagen'),
    ]

    operations = [
    ]
