# Generated by Django 4.2.3 on 2023-07-30 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_merge_20230729_0027'),
        ('noticias', '0005_merge_20230729_1813'),
    ]

    operations = [
    ]
